AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: A Lambda function to that sends new S3 uploads to ChildSafe.io for analysis

Resources:
  SendToChildSafeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Policies: AmazonS3ReadOnlyAccess
      Runtime: nodejs6.10
      CodeUri: s3://childsafe.eddiezane.com/lambda.zip
