# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-12 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='childsafeuser',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='childsafeuser',
            name='phone_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='childsafeuser',
            name='sms_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
