# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-11 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('status', models.CharField(default='received', max_length=255)),
                ('scanned', models.BooleanField(default=False)),
                ('postive', models.BooleanField(default=False)),
                ('alerted', models.BooleanField(default=False)),
            ],
        ),
    ]
