# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-11 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='resource_id',
            field=models.CharField(default='derp', max_length=255),
            preserve_default=False,
        ),
    ]
