# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-11 21:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
        ('media', '0003_auto_20171111_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mediaitems', to='web.ChildsafeUser'),
        ),
    ]
