# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-12 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
        ('media', '0004_mediaitem_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resource_id', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('risk', models.CharField(max_length=255)),
                ('notified', models.BooleanField(default=False)),
                ('mediaitem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='media.MediaItem')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='web.ChildsafeUser')),
            ],
        ),
    ]
